Front end for authorisation done with a login page
RemyKainos/sprint-team-2-front-end pull request #5
Opened 2023-09-13 08:40 UTC by mateenparkar

<img width="1440" alt="image" src="https://github.com/RemyKainos/sprint-team-2-front-end/assets/31510920/514b9b6f-d496-4433-8bc9-b34fece9ec64">

2023-09-13 09:58 UTC, TomBillingtonUK commented
Missing unit tests

2023-09-15 10:04 UTC, TomBillingtonUK commented on test/unit/authServiceTest.ts
> +});
Missing a unit test for the 401 path

2023-09-15 14:33 UTC, mateenparkar commented on test/ui/LoginTests.ts
> +});
For a ui test aren't we just testing the error that displays on the front end? Which is the "Your email or password combination is incorrect" error so we wouldn't have to test the Could not login error?

2023-09-19 09:46 UTC, shaunganley requested changes

2023-09-19 09:46 UTC, shaunganley commented on src/controller/authController.ts
> +export const authController = (app:Application) =>{
it looks like this file isn't used

2023-09-19 09:46 UTC, shaunganley commented on src/service/authService.ts
> +        const response = await axios.post('http://localhost:8080/api/login/', credentials);
still needs to be addressed

2023-09-19 09:46 UTC, shaunganley commented on test/ui/LoginTests.ts
> +        await driver.findElement(By.id('password')).sendKeys('password');
you should pass valid username and password and ENV VARs

2023-09-19 09:46 UTC, shaunganley commented on test/ui/LoginTests.ts
> +        await driver.findElement(By.id('submit')).click();
this should check that you get redirected after successful login

2023-09-19 09:46 UTC, shaunganley commented on test/unit/authServiceTest.ts
> +        mock.onPost('http://localhost:8080/api/login/', loginData).reply(200, responseData);
don't hardcode URL

2023-09-19 09:46 UTC, shaunganley commented on test/unit/authServiceTest.ts
> +        mock.onPost('http://localhost:8080/api/login/', loginData).reply(401, {}); // Simulate a 401 error
```suggestion
        mock.onPost('http://localhost:8080/api/login/', loginData).reply(500);
```

2023-09-19 13:26 UTC, shaunganley approved these changes

2023-09-20 10:19 UTC, Adaray786 approved these changes

2023-09-20 10:20 UTC, merged