Us001 view roles
RemyKainos/sprint-team-2-front-end pull request #9
Opened 2023-09-15 08:58 UTC by CallumE74

2023-09-18 15:48 UTC, Adaray786 commented on package.json
> +    "test": "mocha --require ts-node/register test/unit/**/*.ts"
Add how to run the tests in the ReadMe

2023-09-19 10:04 UTC, shaunganley requested changes

2023-09-19 10:04 UTC, shaunganley commented on src/service/JobRoleService.ts
> +        const response = await axios.get('http://localhost:8080/api/job-roles')
don't hardcode base URL, pass via ENV VAR

2023-09-19 10:04 UTC, shaunganley commented on test/ui/JobRoleUITests.ts
> +            await driver.get('http://localhost:3000/ViewRoles')
don't hardcode base URL, pass via ENV VAR

2023-09-19 11:04 UTC, shaunganley approved these changes
approved but looks like the build isn't running on this PR, might need rebased with main

2023-09-20 10:25 UTC, Adaray786 approved these changes
lgtm

2023-09-21 14:25 UTC, merged